import type { Project, CreateProjectResponse } from './project';
import type { Transcript } from './transcript';
import type { Job } from './job';
import type { MediaMetadata } from './media';
import type { SubtitleTrack } from './subtitle';

export interface CommandMap {
  health_check: {
    args: undefined;
    result: string;
  };
  create_project_cmd: {
    args: { title: string };
    result: Project;
  };
  create_project_from_youtube_cmd: {
    args: { url: string; projectId?: string };
    result: Project;
  };
  rename_project_cmd: {
    args: { projectId: string; title: string };
    result: Project;
  };
  open_project_folder_cmd: {
    args: { projectId: string };
    result: null;
  };
  start_project_mock_pipeline_cmd: {
    args: {
      projectId: string;
      subtitleTrackId?: string;
      subtitleLanguage?: string;
      subtitleAutoGenerated?: boolean;
    };
    result: CreateProjectResponse;
  };
  list_youtube_subtitle_tracks_cmd: {
    args: { projectId: string };
    result: SubtitleTrack[];
  };
  get_transcript_cmd: {
    args: { projectId: string };
    result: Transcript | null;
  };
  get_project_cmd: {
    args: { projectId: string };
    result: Project;
  };
  list_projects_cmd: {
    args: undefined;
    result: Project[];
  };
  delete_project_cmd: {
    args: { projectId: string };
    result: null;
  };

  list_jobs_cmd: {
    args: undefined;
    result: Job[];
  };
  list_jobs_snapshot_cmd: {
    args: { projectId: string };
    result: Job[];
  };
  cancel_job_cmd: {
    args: { jobId: string };
    result: Job;
  };
  probe_local_media_cmd: {
    args: { path: string };
    result: MediaMetadata;
  };
  import_local_media_cmd: {
    args: { projectId: string; path: string };
    result: Project;
  };
}
