// @vitest-environment jsdom
import { act, renderHook, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { useYoutubeSubtitleTracks } from './useYoutubeSubtitleTracks';

const listTracks = vi.hoisted(() => vi.fn());

vi.mock('../api/transcriptApi', () => ({
  listYoutubeSubtitleTracks: listTracks,
}));

const cachedTrack = {
  id: 'ru-auto-vtt',
  language: 'ru',
  label: 'Russian',
  format: 'vtt',
  isAutoGenerated: true,
};

beforeEach(() => {
  listTracks.mockReset();
  localStorage.clear();
});

describe('useYoutubeSubtitleTracks', () => {
  it('shows persistent cache immediately and refreshes it in the background', async () => {
    const projectId = 'persistent-cache-project';
    localStorage.setItem(
      `auralis:youtube-subtitle-tracks:v1:${projectId}`,
      JSON.stringify({ cachedAt: 1, tracks: [cachedTrack] }),
    );
    let resolveTracks: (tracks: (typeof cachedTrack)[]) => void = () => undefined;
    listTracks.mockReturnValue(
      new Promise((resolve) => {
        resolveTracks = resolve;
      }),
    );

    const { result } = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(result.current.tracks).toEqual([cachedTrack]));
    expect(result.current.isLoading).toBe(true);

    const refreshed = [{ ...cachedTrack, id: 'ru-manual-vtt', isAutoGenerated: false }];
    await act(async () => resolveTracks(refreshed));
    await waitFor(() => expect(result.current.tracks).toEqual(refreshed));
    expect(
      JSON.parse(localStorage.getItem(`auralis:youtube-subtitle-tracks:v1:${projectId}`) || '{}')
        .tracks,
    ).toEqual(refreshed);
  });

  it('does not request the same project again during the current session', async () => {
    const projectId = 'session-cache-project';
    listTracks.mockResolvedValue([cachedTrack]);
    const first = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(first.result.current.isLoading).toBe(false));
    first.unmount();

    const second = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(second.result.current.tracks).toEqual([cachedTrack]));
    expect(listTracks).toHaveBeenCalledTimes(1);
  });

  it('retries automatically after a failed load and remount', async () => {
    const projectId = 'failed-load-remount-project';
    listTracks.mockRejectedValueOnce(new Error('network unavailable'));

    const first = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(first.result.current.error).not.toBeNull());
    first.unmount();

    listTracks.mockResolvedValueOnce([cachedTrack]);
    const second = renderHook(() => useYoutubeSubtitleTracks(projectId));

    await waitFor(() => expect(second.result.current.tracks).toEqual([cachedTrack]));
    expect(second.result.current.error).toBeNull();
    expect(listTracks).toHaveBeenCalledTimes(2);
  });

  it('keeps a pending load useful after leaving and returning to its project', async () => {
    const projectA = 'pending-return-project-a';
    const projectB = 'pending-return-project-b';
    const pendingA = deferred<(typeof cachedTrack)[]>();
    listTracks.mockImplementation((projectId: string) =>
      projectId === projectA ? pendingA.promise : Promise.resolve([]),
    );

    const { result, rerender } = renderHook(
      ({ projectId }: { projectId: string | null }) => useYoutubeSubtitleTracks(projectId),
      { initialProps: { projectId: projectA as string | null } },
    );
    await waitFor(() => expect(result.current.isLoading).toBe(true));

    rerender({ projectId: projectB });
    await waitFor(() => expect(result.current.isLoading).toBe(false));
    await act(async () => pendingA.resolve([cachedTrack]));

    rerender({ projectId: projectA });
    await waitFor(() => expect(result.current.tracks).toEqual([cachedTrack]));
    expect(listTracks.mock.calls.filter(([id]) => id === projectA)).toHaveLength(1);
  });

  it('clears tracks and request state when the project scope changes or closes', async () => {
    const projectA = 'scope-reset-project-a';
    const projectB = 'scope-reset-project-b';
    const pendingB = deferred<(typeof cachedTrack)[]>();
    listTracks.mockImplementation((projectId: string) =>
      projectId === projectA ? Promise.resolve([cachedTrack]) : pendingB.promise,
    );

    const { result, rerender } = renderHook(
      ({ projectId }: { projectId: string | null }) => useYoutubeSubtitleTracks(projectId),
      { initialProps: { projectId: projectA as string | null } },
    );
    await waitFor(() => expect(result.current.tracks).toEqual([cachedTrack]));

    rerender({ projectId: projectB });
    expect(result.current.tracks).toEqual([]);
    expect(result.current.error).toBeNull();
    await waitFor(() => expect(result.current.isLoading).toBe(true));

    rerender({ projectId: null });
    expect(result.current.tracks).toEqual([]);
    expect(result.current.isLoading).toBe(false);
    expect(result.current.error).toBeNull();

    await act(async () => pendingB.resolve([{ ...cachedTrack, language: 'en' }]));
    expect(result.current.tracks).toEqual([]);
    expect(result.current.isLoading).toBe(false);
  });

  it('shares one pending request between observers of the same project', async () => {
    const projectId = 'shared-pending-project';
    const pending = deferred<(typeof cachedTrack)[]>();
    listTracks.mockReturnValue(pending.promise);

    const first = renderHook(() => useYoutubeSubtitleTracks(projectId));
    const second = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => {
      expect(first.result.current.isLoading).toBe(true);
      expect(second.result.current.isLoading).toBe(true);
    });
    expect(listTracks).toHaveBeenCalledTimes(1);

    await act(async () => pending.resolve([cachedTrack]));
    await waitFor(() => {
      expect(first.result.current.tracks).toEqual([cachedTrack]);
      expect(second.result.current.tracks).toEqual([cachedTrack]);
    });
  });

  it('forces a new request after a successful session refresh', async () => {
    const projectId = 'forced-refresh-project';
    const refreshed = [{ ...cachedTrack, id: 'ru-manual-vtt', isAutoGenerated: false }];
    listTracks.mockResolvedValueOnce([cachedTrack]).mockResolvedValueOnce(refreshed);

    const { result } = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(result.current.tracks).toEqual([cachedTrack]));

    await act(async () => result.current.refresh());

    expect(result.current.tracks).toEqual(refreshed);
    expect(result.current.isLoading).toBe(false);
    expect(listTracks).toHaveBeenCalledTimes(2);
  });
});

function deferred<T>() {
  let resolve: (value: T) => void = () => undefined;
  let reject: (reason?: unknown) => void = () => undefined;
  const promise = new Promise<T>((resolvePromise, rejectPromise) => {
    resolve = resolvePromise;
    reject = rejectPromise;
  });
  return { promise, reject, resolve };
}
