import { useCallback, useEffect, useRef, useState } from 'react';
import { toCommandError } from '@/shared/api/contracts';
import type { SubtitleTrack } from '@/shared/api/contracts/subtitle';
import { listYoutubeSubtitleTracks } from '../api/transcriptApi';

type CachedTracks = {
  cachedAt: number;
  tracks: SubtitleTrack[];
};

const CACHE_PREFIX = 'auralis:youtube-subtitle-tracks:v1:';
const memoryCache = new Map<string, CachedTracks>();
const refreshedThisSession = new Set<string>();

export function useYoutubeSubtitleTracks(projectId: string | null) {
  const [tracks, setTracks] = useState<SubtitleTrack[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const requestIdRef = useRef(0);
  const activeProjectIdRef = useRef(projectId);
  activeProjectIdRef.current = projectId;

  const load = useCallback(
    async (force = false) => {
      if (!projectId) {
        requestIdRef.current += 1;
        setTracks([]);
        setError(null);
        return;
      }

      const cached = readCache(projectId);
      if (cached) {
        setTracks(cached.tracks);
        setError(null);
      }

      if (!force && refreshedThisSession.has(projectId)) return;
      const requestId = ++requestIdRef.current;
      refreshedThisSession.add(projectId);
      setIsLoading(true);
      try {
        const result = await listYoutubeSubtitleTracks(projectId);
        if (requestId !== requestIdRef.current || activeProjectIdRef.current !== projectId) return;
        writeCache(projectId, result);
        setTracks(result);
        setError(null);
      } catch (cause) {
        if (requestId !== requestIdRef.current || activeProjectIdRef.current !== projectId) return;
        if (!cached) setError(toCommandError(cause).message);
      } finally {
        if (requestId === requestIdRef.current && activeProjectIdRef.current === projectId) {
          setIsLoading(false);
        }
      }
    },
    [projectId],
  );

  useEffect(() => {
    void load();
  }, [load]);

  return {
    tracks,
    isLoading,
    error,
    refresh: () => load(true),
  };
}

function cacheKey(projectId: string): string {
  return `${CACHE_PREFIX}${projectId}`;
}

function readCache(projectId: string): CachedTracks | null {
  const memoryValue = memoryCache.get(projectId);
  if (memoryValue) return memoryValue;

  try {
    const raw = globalThis.localStorage?.getItem(cacheKey(projectId));
    if (!raw) return null;
    const parsed: unknown = JSON.parse(raw);
    if (!isCachedTracks(parsed)) {
      globalThis.localStorage?.removeItem(cacheKey(projectId));
      return null;
    }
    memoryCache.set(projectId, parsed);
    return parsed;
  } catch {
    return null;
  }
}

function writeCache(projectId: string, tracks: SubtitleTrack[]) {
  const value: CachedTracks = { cachedAt: Date.now(), tracks };
  memoryCache.set(projectId, value);
  try {
    globalThis.localStorage?.setItem(cacheKey(projectId), JSON.stringify(value));
  } catch {
    // Persistent cache is an optimization; the in-memory cache remains available.
  }
}

function isCachedTracks(value: unknown): value is CachedTracks {
  if (!value || typeof value !== 'object') return false;
  const candidate = value as { cachedAt?: unknown; tracks?: unknown };
  return (
    typeof candidate.cachedAt === 'number' &&
    Array.isArray(candidate.tracks) &&
    candidate.tracks.every(isSubtitleTrack)
  );
}

function isSubtitleTrack(value: unknown): value is SubtitleTrack {
  if (!value || typeof value !== 'object') return false;
  const track = value as Record<string, unknown>;
  return (
    typeof track.id === 'string' &&
    typeof track.language === 'string' &&
    (typeof track.label === 'string' || track.label === null) &&
    (typeof track.format === 'string' || track.format === null) &&
    typeof track.isAutoGenerated === 'boolean'
  );
}
