// @vitest-environment jsdom
import { act, renderHook, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { useYoutubeSubtitleTracks } from './useYoutubeSubtitleTracks';

const listTracks = vi.hoisted(() => vi.fn());

vi.mock('../api/transcriptApi', () => ({
  listYoutubeSubtitleTracks: listTracks,
}));

const cachedTrack = {
  id: 'ru-auto-vtt',
  language: 'ru',
  label: 'Russian',
  format: 'vtt',
  isAutoGenerated: true,
};

beforeEach(() => {
  vi.clearAllMocks();
  localStorage.clear();
});

describe('useYoutubeSubtitleTracks', () => {
  it('shows persistent cache immediately and refreshes it in the background', async () => {
    const projectId = 'persistent-cache-project';
    localStorage.setItem(
      `auralis:youtube-subtitle-tracks:v1:${projectId}`,
      JSON.stringify({ cachedAt: 1, tracks: [cachedTrack] }),
    );
    let resolveTracks: (tracks: (typeof cachedTrack)[]) => void = () => undefined;
    listTracks.mockReturnValue(
      new Promise((resolve) => {
        resolveTracks = resolve;
      }),
    );

    const { result } = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(result.current.tracks).toEqual([cachedTrack]));
    expect(result.current.isLoading).toBe(true);

    const refreshed = [{ ...cachedTrack, id: 'ru-manual-vtt', isAutoGenerated: false }];
    await act(async () => resolveTracks(refreshed));
    await waitFor(() => expect(result.current.tracks).toEqual(refreshed));
    expect(
      JSON.parse(localStorage.getItem(`auralis:youtube-subtitle-tracks:v1:${projectId}`) || '{}')
        .tracks,
    ).toEqual(refreshed);
  });

  it('does not request the same project again during the current session', async () => {
    const projectId = 'session-cache-project';
    listTracks.mockResolvedValue([cachedTrack]);
    const first = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(first.result.current.isLoading).toBe(false));
    first.unmount();

    const second = renderHook(() => useYoutubeSubtitleTracks(projectId));
    await waitFor(() => expect(second.result.current.tracks).toEqual([cachedTrack]));
    expect(listTracks).toHaveBeenCalledTimes(1);
  });
});
