use adapters_storage::memory::InMemoryProjectRepository;
use adapters_ytdlp::mock::MockVideoSourceAdapter;
use application::usecases::pipeline::start_mock::{
    StartMockPipelineRequest, StartMockPipelineUseCase,
};
use application::usecases::project::create::{CreateProjectRequest, CreateProjectUseCase};
use application::usecases::project::import_source::{
    ImportVideoSourceRequest, ImportVideoSourceUseCase,
};
use domain::media::MediaSource;
use jobs::manager::JobManager;
use tauri::{command, State};

use crate::dto::project::{CreateProjectResponse, ProjectDto, TranscriptDto, TranscriptSegmentDto};

#[command]
pub async fn create_project_cmd(
    title: String,
    project_repo: State<'_, InMemoryProjectRepository>,
) -> Result<ProjectDto, String> {
    let create_use_case = CreateProjectUseCase::new(project_repo.inner().clone());
    let req = CreateProjectRequest { title };
    let create_res = create_use_case
        .execute(req)
        .await
        .map_err(|e| format!("{:?}", e))?;

    Ok(ProjectDto::from(&create_res.project))
}

#[command]
pub async fn create_project_from_youtube_cmd(
    url: String,
    state: State<'_, JobManager>,
    project_repo: State<'_, InMemoryProjectRepository>,
) -> Result<CreateProjectResponse, String> {
    let create_use_case = CreateProjectUseCase::new(project_repo.inner().clone());
    let req = CreateProjectRequest { title: url.clone() };
    let create_res = create_use_case
        .execute(req)
        .await
        .map_err(|e| format!("{:?}", e))?;

    let mock_video_source = MockVideoSourceAdapter::new();
    let import_use_case =
        ImportVideoSourceUseCase::new(project_repo.inner().clone(), mock_video_source);
    let source = MediaSource::RemoteUrl { url };
    let req2 = ImportVideoSourceRequest {
        project_id: create_res.project.id().clone(),
        source,
    };
    let import_res = import_use_case
        .execute(req2)
        .await
        .map_err(|e| format!("{:?}", e))?;

    let pipeline_use_case =
        StartMockPipelineUseCase::new(project_repo.inner().clone(), state.inner().clone());
    let req3 = StartMockPipelineRequest {
        project_id: import_res.project.id().clone(),
    };
    let response = pipeline_use_case
        .execute(req3)
        .await
        .map_err(|e| format!("{:?}", e))?;

    Ok(CreateProjectResponse {
        project: ProjectDto::from(&response.project),
        job: response.job,
    })
}

#[command]
pub async fn get_transcript_cmd(_project_id: String) -> Result<Option<TranscriptDto>, String> {
    Ok(Some(TranscriptDto {
        language: "en".to_string(),
        segments: vec![
            TranscriptSegmentDto {
                id: "1".to_string(),
                index: 0,
                start_ms: 0,
                end_ms: 2000,
                source_text: "Welcome to Auralis.".to_string(),
            },
            TranscriptSegmentDto {
                id: "2".to_string(),
                index: 1,
                start_ms: 2000,
                end_ms: 5000,
                source_text: "This is a mock transcript generated by the backend.".to_string(),
            },
        ],
    }))
}

#[command]
pub fn run_dubbing_cmd(video_url: String) -> Result<String, String> {
    application::commands::run_dubbing(video_url)
}
