import { invoke } from '@/shared/api/tauri';
import type { Project, CreateProjectResponse } from '../model/types';
import type { SubtitleTrack } from '@/shared/api/contracts/subtitle';
import { youtubeImportsChanged } from '../model/youtubeImportChanges';

export async function createProjectFromYoutube(url: string, projectId?: string): Promise<Project> {
  try {
    return await invoke('create_project_from_youtube_cmd', {
      url,
      ...(projectId ? { projectId } : {}),
    });
  } finally {
    youtubeImportsChanged();
  }
}

export async function startProjectMockPipeline(
  projectId: string,
  subtitleTrack?: SubtitleTrack,
): Promise<CreateProjectResponse> {
  return invoke('start_project_mock_pipeline_cmd', {
    projectId,
    ...(subtitleTrack
      ? {
          subtitleTrackId: subtitleTrack.id,
          subtitleLanguage: subtitleTrack.language,
          subtitleAutoGenerated: subtitleTrack.isAutoGenerated,
        }
      : {}),
  });
}

export async function createProject(title: string): Promise<Project> {
  return invoke('create_project_cmd', { title });
}

export async function listProjects(): Promise<Project[]> {
  return invoke('list_projects_cmd');
}

export async function deleteProject(projectId: string): Promise<void> {
  await invoke('delete_project_cmd', { projectId });
}

export async function renameProject(projectId: string, title: string): Promise<Project> {
  return invoke('rename_project_cmd', { projectId, title });
}

export async function openProjectFolder(projectId: string): Promise<void> {
  await invoke('open_project_folder_cmd', { projectId });
}
