import { beforeEach, describe, expect, it, vi } from 'vitest';
import { invoke } from '@/shared/api/tauri';
import type { SubtitleTrack } from '@/shared/api/contracts/subtitle';
import type { Project } from '../model/types';
import { youtubeImportsChanged } from '../model/youtubeImportChanges';
import {
  createProject,
  createProjectFromYoutube,
  deleteProject,
  listProjects,
  openProjectFolder,
  renameProject,
  startProjectMockPipeline,
} from './projectApi';

vi.mock('@/shared/api/tauri', () => ({
  invoke: vi.fn(),
}));

vi.mock('../model/youtubeImportChanges', () => ({
  youtubeImportsChanged: vi.fn(),
}));

const project: Project = {
  id: 'project-1',
  title: 'Project',
  status: 'draft',
  source: null,
  metadata: null,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
};

describe('projectApi', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('creates a new YouTube project and announces the completed attempt', async () => {
    vi.mocked(invoke).mockResolvedValueOnce(project as never);

    const result = await createProjectFromYoutube('https://youtube.com/watch?v=video');

    expect(result).toBe(project);
    expect(invoke).toHaveBeenCalledExactlyOnceWith('create_project_from_youtube_cmd', {
      url: 'https://youtube.com/watch?v=video',
    });
    expect(youtubeImportsChanged).toHaveBeenCalledOnce();
  });

  it('keeps the retry project id and announces a failed YouTube attempt', async () => {
    const failure = new Error('Import failed');
    vi.mocked(invoke).mockRejectedValueOnce(failure);

    await expect(
      createProjectFromYoutube('https://youtube.com/watch?v=video', 'project-1'),
    ).rejects.toBe(failure);

    expect(invoke).toHaveBeenCalledExactlyOnceWith('create_project_from_youtube_cmd', {
      url: 'https://youtube.com/watch?v=video',
      projectId: 'project-1',
    });
    expect(youtubeImportsChanged).toHaveBeenCalledOnce();
  });

  it('starts the pipeline without optional subtitle arguments', async () => {
    await startProjectMockPipeline('project-1');

    expect(invoke).toHaveBeenCalledExactlyOnceWith('start_project_mock_pipeline_cmd', {
      projectId: 'project-1',
    });
  });

  it('maps a selected subtitle track to the backend contract', async () => {
    const subtitleTrack: SubtitleTrack = {
      id: 'subtitle-1',
      language: 'ru',
      label: 'Russian',
      format: 'vtt',
      isAutoGenerated: true,
    };

    await startProjectMockPipeline('project-1', subtitleTrack);

    expect(invoke).toHaveBeenCalledExactlyOnceWith('start_project_mock_pipeline_cmd', {
      projectId: 'project-1',
      subtitleTrackId: 'subtitle-1',
      subtitleLanguage: 'ru',
      subtitleAutoGenerated: true,
    });
  });

  it('maps project CRUD operations to their commands', async () => {
    vi.mocked(invoke)
      .mockResolvedValueOnce(project as never)
      .mockResolvedValueOnce([project] as never)
      .mockResolvedValueOnce(null as never)
      .mockResolvedValueOnce(project as never)
      .mockResolvedValueOnce(null as never);

    await expect(createProject('Project')).resolves.toBe(project);
    await expect(listProjects()).resolves.toEqual([project]);
    await expect(deleteProject('project-1')).resolves.toBeUndefined();
    await expect(renameProject('project-1', 'Renamed')).resolves.toBe(project);
    await expect(openProjectFolder('project-1')).resolves.toBeUndefined();

    expect(invoke).toHaveBeenNthCalledWith(1, 'create_project_cmd', { title: 'Project' });
    expect(invoke).toHaveBeenNthCalledWith(2, 'list_projects_cmd');
    expect(invoke).toHaveBeenNthCalledWith(3, 'delete_project_cmd', {
      projectId: 'project-1',
    });
    expect(invoke).toHaveBeenNthCalledWith(4, 'rename_project_cmd', {
      projectId: 'project-1',
      title: 'Renamed',
    });
    expect(invoke).toHaveBeenNthCalledWith(5, 'open_project_folder_cmd', {
      projectId: 'project-1',
    });
  });
});
