// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { SubtitleWorkspace } from './SubtitleWorkspace';

const refreshTracks = vi.fn();
const mockUseTranscript = vi.hoisted(() => vi.fn());

vi.mock('@/entities/project', () => ({
  useProjectContext: () => ({ project: { id: 'project-1' } }),
}));

vi.mock('@/entities/job', () => ({
  useProjectJobs: () => ({ jobs: [] }),
}));

vi.mock('@/entities/transcript', () => ({
  useTranscript: mockUseTranscript,
  useYoutubeSubtitleTracks: () => ({
    tracks: [
      {
        id: 'ru-auto-vtt',
        language: 'ru',
        label: 'Russian',
        format: 'vtt',
        isAutoGenerated: true,
      },
      {
        id: 'en-manual-vtt',
        language: 'en',
        label: 'English',
        format: 'vtt',
        isAutoGenerated: false,
      },
    ],
    isLoading: false,
    error: null,
    refresh: refreshTracks,
  }),
}));

vi.mock('@/features/run-dubbing', () => ({
  RunDubbing: ({ subtitleTrack }: { subtitleTrack: { id: string } | null }) => (
    <button type="button">Import {subtitleTrack?.id}</button>
  ),
}));

afterEach(() => cleanup());

beforeEach(() => {
  vi.clearAllMocks();
  mockUseTranscript.mockReturnValue({
    transcript: null,
    isLoading: false,
    error: null,
    refetch: vi.fn(),
  });
});

describe('SubtitleWorkspace', () => {
  it('selects the first Russian-priority track and allows choosing another track', () => {
    render(<SubtitleWorkspace />);

    expect(screen.getByRole('button', { name: 'Import ru-auto-vtt' })).not.toBeNull();
    fireEvent.click(screen.getByText(/Английский/));
    expect(screen.getByRole('button', { name: 'Import en-manual-vtt' })).not.toBeNull();
  });

  it('refreshes YouTube tracks only from the explicit update action', () => {
    render(<SubtitleWorkspace />);
    fireEvent.click(screen.getByRole('button', { name: 'Обновить' }));
    expect(refreshTracks).toHaveBeenCalledTimes(1);
  });

  it('filters tracks locally without refreshing YouTube', () => {
    render(<SubtitleWorkspace />);
    fireEvent.change(screen.getByRole('searchbox', { name: 'Поиск по доступным дорожкам' }), {
      target: { value: 'авторские' },
    });

    expect(screen.queryByText(/Русский/)).toBeNull();
    expect(screen.getByText(/Английский/)).not.toBeNull();
    expect(refreshTracks).not.toHaveBeenCalled();
  });

  it('searches locally through all received subtitle segments', () => {
    mockUseTranscript.mockReturnValue({
      transcript: {
        language: 'ru',
        segments: [
          { id: '1', index: 0, startMs: 0, endMs: 1000, sourceText: 'Первая реплика' },
          { id: '2', index: 1, startMs: 1000, endMs: 2000, sourceText: 'Нужный фрагмент' },
        ],
      },
      isLoading: false,
      error: null,
      refetch: vi.fn(),
    });
    render(<SubtitleWorkspace />);
    fireEvent.change(screen.getByRole('searchbox', { name: 'Поиск по тексту субтитров' }), {
      target: { value: 'нужный' },
    });

    expect(screen.getByText('Нужный фрагмент')).not.toBeNull();
    expect(screen.queryByText('Первая реплика')).toBeNull();
    expect(screen.getByText('Найдено реплик: 1')).not.toBeNull();
  });
});
