import { useEffect, useMemo, useState } from 'react';
import { useProjectJobs } from '@/entities/job';
import { useProjectContext } from '@/entities/project';
import { useTranscript, useYoutubeSubtitleTracks, type SubtitleTrack } from '@/entities/transcript';
import { RunDubbing } from '@/features/run-dubbing';
import { Button } from '@/shared/ui/button';
import { Icon } from '@/shared/ui/icon';

export function SubtitleWorkspace() {
  const { project } = useProjectContext();
  const { jobs } = useProjectJobs(project?.id ?? null);
  const {
    transcript,
    isLoading: transcriptLoading,
    error: transcriptError,
    refetch,
  } = useTranscript(project?.id ?? null);
  const { tracks, isLoading, error, refresh } = useYoutubeSubtitleTracks(project?.id ?? null);
  const [selectedTrackId, setSelectedTrackId] = useState<string | null>(null);
  const [trackQuery, setTrackQuery] = useState('');

  useEffect(() => {
    if (tracks.length === 0) {
      setSelectedTrackId(null);
      return;
    }
    setSelectedTrackId((current) =>
      current && tracks.some((track) => track.id === current) ? current : tracks[0].id,
    );
  }, [tracks]);

  const selectedTrack = tracks.find((track) => track.id === selectedTrackId) ?? null;
  const filteredTracks = useMemo(() => {
    const query = trackQuery.trim().toLocaleLowerCase('ru-RU');
    if (!query) return tracks;
    return tracks.filter((track) =>
      [
        track.language,
        track.label || '',
        languageName(track.language),
        track.isAutoGenerated ? 'авто автоматические' : 'авторские ручные',
      ].some((value) => value.toLocaleLowerCase('ru-RU').includes(query)),
    );
  }, [trackQuery, tracks]);
  const activity = useMemo(
    () => [...jobs].sort((left, right) => left.updatedAt.localeCompare(right.updatedAt)),
    [jobs],
  );
  const isRunning = activity.some((job) => job.status === 'pending' || job.status === 'running');

  return (
    <section
      className="h-full min-h-0 overflow-y-auto px-4 py-5 sm:px-6"
      aria-label="Subtitle source configuration"
      data-testid="subtitle-workspace"
    >
      <div className="space-y-5">
        <WorkspaceSection title="Способ получения">
          <div className="space-y-2">
            <MethodRow
              title="YouTube-субтитры"
              description="Авторские или автоматически созданные дорожки"
              selected
            />
            <MethodRow
              title="Импорт SRT"
              description="Импорт готового файла пока не подключён"
              disabled
            />
            <MethodRow
              title="Speech-to-Text"
              description="Распознавание речи пока не подключено"
              disabled
            />
          </div>
        </WorkspaceSection>

        <WorkspaceSection
          title="Доступные дорожки"
          action={
            <Button variant="ghost" size="sm" onClick={() => void refresh()} disabled={isLoading}>
              {isLoading ? 'Обновление…' : 'Обновить'}
            </Button>
          }
        >
          <div className="relative mb-2">
            <Icon
              name="Search"
              size={13}
              color="muted"
              className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2"
            />
            <input
              type="search"
              value={trackQuery}
              onChange={(event) => setTrackQuery(event.target.value)}
              placeholder="Поиск по языку или типу дорожки…"
              aria-label="Поиск по доступным дорожкам"
              className="h-9 w-full rounded-md border border-border bg-surface-raised pl-8 pr-3 text-xs text-text outline-none placeholder:text-subtle focus:border-primary focus:ring-2 focus:ring-primary/20"
            />
          </div>
          <TrackList
            tracks={filteredTracks}
            selectedTrackId={selectedTrackId}
            onSelect={setSelectedTrackId}
            isLoading={isLoading}
            error={error}
            hasQuery={Boolean(trackQuery.trim())}
          />
          <div className="mt-3 flex justify-end">
            <RunDubbing
              subtitleTrack={selectedTrack}
              label={transcript ? 'Получить заново' : 'Получить субтитры'}
              disabled={!selectedTrack || isLoading || isRunning}
            />
          </div>
        </WorkspaceSection>

        {(transcriptLoading || transcriptError || transcript) && (
          <TranscriptResult
            transcript={transcript}
            isLoading={transcriptLoading}
            error={transcriptError}
            onRefresh={refetch}
          />
        )}

        <WorkspaceSection title="Лог">
          <div className="min-h-[76px] rounded-md border border-border bg-canvas px-3 py-2.5 font-mono text-[11px] leading-5">
            {activity.length === 0 ? (
              <p className="text-subtle">Импорт субтитров ещё не запускался</p>
            ) : (
              activity.map((job) => (
                <div key={job.id} className="flex min-w-0 gap-3">
                  <span className="shrink-0 text-subtle">{formatTime(job.updatedAt)}</span>
                  <span
                    className={
                      job.status === 'failed'
                        ? 'min-w-0 break-words text-danger'
                        : 'min-w-0 break-words text-muted'
                    }
                  >
                    {job.status === 'failed'
                      ? job.error || 'Ошибка импорта субтитров'
                      : job.progress.message || formatJobStatus(job.status)}
                  </span>
                </div>
              ))
            )}
          </div>
        </WorkspaceSection>
      </div>
    </section>
  );
}

function WorkspaceSection({
  title,
  action,
  children,
}: {
  title: string;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <section aria-labelledby={`subtitle-${slug(title)}`}>
      <div className="mb-2 flex min-h-7 items-center justify-between gap-3">
        <h2 id={`subtitle-${slug(title)}`} className="text-xs font-semibold text-muted">
          {title}
        </h2>
        {action}
      </div>
      {children}
    </section>
  );
}

function MethodRow({
  title,
  description,
  selected = false,
  disabled = false,
}: {
  title: string;
  description: string;
  selected?: boolean;
  disabled?: boolean;
}) {
  return (
    <div
      className={`flex min-h-[50px] items-center gap-3 rounded-md border px-3 py-2.5 ${
        selected ? 'border-primary/60 bg-primary/10' : 'border-border bg-surface-raised opacity-65'
      }`}
      aria-disabled={disabled || undefined}
    >
      <span
        className={`h-3 w-3 rounded-full border ${
          selected
            ? 'border-primary bg-primary shadow-[inset_0_0_0_3px_var(--color-bg)]'
            : 'border-border-strong'
        }`}
        aria-hidden="true"
      />
      <span>
        <span className="block text-xs font-semibold text-text">{title}</span>
        <span className="mt-0.5 block text-[11px] text-subtle">{description}</span>
      </span>
    </div>
  );
}

function TrackList({
  tracks,
  selectedTrackId,
  onSelect,
  isLoading,
  error,
  hasQuery,
}: {
  tracks: SubtitleTrack[];
  selectedTrackId: string | null;
  onSelect: (id: string) => void;
  isLoading: boolean;
  error: string | null;
  hasQuery: boolean;
}) {
  if (isLoading && tracks.length === 0) {
    return <StatusBox text="Получаем список дорожек с YouTube…" />;
  }
  if (error) {
    return <StatusBox text={error} danger />;
  }
  if (tracks.length === 0) {
    return (
      <StatusBox
        text={
          hasQuery
            ? 'По этому запросу дорожек не найдено'
            : 'YouTube не вернул доступных VTT-дорожек'
        }
      />
    );
  }

  return (
    <div className="overflow-hidden rounded-md border border-border bg-surface" role="radiogroup">
      {tracks.map((track, index) => {
        const selected = track.id === selectedTrackId;
        return (
          <label
            key={track.id}
            className={`flex min-h-[34px] cursor-pointer items-center gap-2 border-border px-3 py-2 text-xs transition-colors hover:bg-surface-hover ${
              index > 0 ? 'border-t' : ''
            } ${selected ? 'bg-surface-active text-text' : 'text-muted'}`}
          >
            <input
              type="radio"
              name="youtube-subtitle-track"
              value={track.id}
              checked={selected}
              onChange={() => onSelect(track.id)}
              className="sr-only"
            />
            <span
              className={`h-2.5 w-2.5 rounded-full border ${
                selected ? 'border-primary bg-primary' : 'border-border-strong'
              }`}
              aria-hidden="true"
            />
            <span className="min-w-0 flex-1 truncate font-semibold">
              {languageName(track.language)}
            </span>
            <span
              className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${
                track.isAutoGenerated
                  ? 'border border-border-strong bg-surface text-muted'
                  : 'bg-success/15 text-success'
              }`}
            >
              {track.isAutoGenerated ? 'авто' : 'авторские'}
            </span>
          </label>
        );
      })}
    </div>
  );
}

function TranscriptResult({
  transcript,
  isLoading,
  error,
  onRefresh,
}: {
  transcript: ReturnType<typeof useTranscript>['transcript'];
  isLoading: boolean;
  error: string | null;
  onRefresh: () => void;
}) {
  const [query, setQuery] = useState('');
  if (isLoading) return <StatusBox text="Проверяем полученные субтитры…" />;
  if (error) return <StatusBox text={error} danger />;
  if (!transcript) return null;

  const normalizedQuery = query.trim().toLocaleLowerCase('ru-RU');
  const matchingSegments = normalizedQuery
    ? transcript.segments.filter((segment) =>
        segment.sourceText.toLocaleLowerCase('ru-RU').includes(normalizedQuery),
      )
    : transcript.segments.slice(0, 3);
  const visibleSegments = matchingSegments.slice(0, 50);

  return (
    <section
      className="rounded-md border border-success/60 bg-success/10 p-3"
      aria-label="Полученные субтитры"
    >
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2 text-xs font-semibold text-success">
          <Icon name="CircleCheck" size={14} />
          Субтитры получены
        </div>
        <Button variant="ghost" size="sm" onClick={onRefresh}>
          Обновить
        </Button>
      </div>
      <p className="mt-3 font-mono text-[11px] text-subtle">subtitles/source.vtt</p>
      <div className="mt-3 border-t border-success/25 pt-2">
        <div className="relative mb-2">
          <Icon
            name="Search"
            size={12}
            color="muted"
            className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2"
          />
          <input
            type="search"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Поиск по тексту субтитров…"
            aria-label="Поиск по тексту субтитров"
            className="h-8 w-full rounded-sm border border-success/25 bg-canvas/40 pl-7 pr-3 text-[11px] text-text outline-none placeholder:text-subtle focus:border-primary focus:ring-2 focus:ring-primary/20"
          />
        </div>
        <p className="mb-1.5 text-[10px] text-subtle">
          {normalizedQuery
            ? `Найдено реплик: ${matchingSegments.length}`
            : 'Предпросмотр (первые 3 реплики)'}
        </p>
        {visibleSegments.map((segment) => (
          <div key={segment.id} className="flex gap-2 font-mono text-[11px] leading-5 text-muted">
            <span className="text-primary">{segment.index + 1}</span>
            <span className="text-subtle">{formatRange(segment.startMs, segment.endMs)}</span>
            <span className="min-w-0 break-words text-text">{segment.sourceText}</span>
          </div>
        ))}
        {normalizedQuery && matchingSegments.length === 0 && (
          <p className="py-2 text-[11px] text-subtle">Совпадений в субтитрах нет</p>
        )}
      </div>
    </section>
  );
}

function StatusBox({ text, danger = false }: { text: string; danger?: boolean }) {
  return (
    <div
      className={`rounded-md border px-3 py-4 text-xs ${
        danger
          ? 'border-danger/50 bg-danger/10 text-danger'
          : 'border-border bg-surface text-subtle'
      }`}
      role={danger ? 'alert' : 'status'}
    >
      {text}
    </div>
  );
}

const languageNames = new Intl.DisplayNames(['ru'], { type: 'language' });

function languageName(language: string): string {
  const normalized = language.replace('_', '-');
  const name = languageNames.of(normalized) || language;
  return `${name.charAt(0).toLocaleUpperCase('ru-RU')}${name.slice(1)} (${language})`;
}

function formatTime(value: string): string {
  return new Date(value).toLocaleTimeString('ru-RU', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

function formatRange(startMs: number, endMs: number): string {
  return `${formatTimestamp(startMs)} → ${formatTimestamp(endMs)}`;
}

function formatTimestamp(value: number): string {
  const minutes = Math.floor(value / 60_000);
  const seconds = Math.floor((value % 60_000) / 1000);
  const milliseconds = value % 1000;
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(milliseconds).padStart(3, '0')}`;
}

function formatJobStatus(status: string): string {
  if (status === 'completed') return 'Субтитры получены';
  if (status === 'cancelled') return 'Импорт отменён';
  return 'Ожидание импорта';
}

function slug(value: string): string {
  return value.toLocaleLowerCase('ru-RU').replaceAll(' ', '-');
}
