[package]
name = "jobs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["rt", "time", "macros", "sync"] }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror.workspace = true
domain = { path = "../domain" }
ports = { path = "../ports" }
common = { path = "../common" }
async-trait.workspace = true
tracing.workspace = true
futures.workspace = true

[dev-dependencies]
serde_json.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
