import type { Job } from '@/entities/job';
import type { SubtitleTrack } from '@/entities/transcript';

const languageNames = new Intl.DisplayNames(['ru'], { type: 'language' });

export function filterTracks(tracks: SubtitleTrack[], query: string): SubtitleTrack[] {
  const normalized = query.trim().toLocaleLowerCase('ru-RU');
  if (!normalized) return tracks;
  return tracks.filter((track) =>
    [
      track.language,
      track.label ?? '',
      languageName(track.language),
      track.isAutoGenerated ? 'авто автоматические' : 'авторские ручные',
    ].some((value) => value.toLocaleLowerCase('ru-RU').includes(normalized)),
  );
}

export function languageName(language: string): string {
  const normalized = language.replace('_', '-');
  const name = languageNames.of(normalized) || language;
  return `${name.charAt(0).toLocaleUpperCase('ru-RU')}${name.slice(1)} (${language})`;
}

export function formatRange(startMs: number, endMs: number): string {
  return `${formatTimestamp(startMs)} → ${formatTimestamp(endMs)}`;
}

export function formatJobStatus(status: Job['status']): string {
  if (status === 'completed') return 'Субтитры получены';
  if (status === 'cancelled') return 'Импорт отменён';
  return 'Ожидание импорта';
}

function formatTimestamp(value: number): string {
  const minutes = Math.floor(value / 60_000);
  const seconds = Math.floor((value % 60_000) / 1000);
  const milliseconds = value % 1000;
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(milliseconds).padStart(3, '0')}`;
}
