import type { SubtitleTrack } from '@/entities/transcript';
import { languageName } from './model';
import { StatusBox } from './StatusBox';

type Props = {
  tracks: SubtitleTrack[];
  selectedTrackId: string | null;
  onSelect: (id: string) => void;
  isLoading: boolean;
  error: string | null;
  hasQuery: boolean;
};

export function TrackList(props: Props) {
  const { tracks, selectedTrackId, onSelect, isLoading, error, hasQuery } = props;
  if (isLoading && tracks.length === 0) {
    return <StatusBox text="Получаем список дорожек с YouTube…" />;
  }
  if (error) return <StatusBox text={error} danger />;
  if (tracks.length === 0) {
    return (
      <StatusBox
        text={
          hasQuery
            ? 'По этому запросу дорожек не найдено'
            : 'YouTube не вернул доступных VTT-дорожек'
        }
      />
    );
  }

  return (
    <div
      className="overflow-hidden rounded-md border border-border bg-surface animate-surface-in"
      role="radiogroup"
    >
      {tracks.map((track, index) => {
        const selected = track.id === selectedTrackId;
        return (
          <label
            key={track.id}
            className={`motion-surface flex min-h-[34px] cursor-pointer items-center gap-2 border-border px-3 py-2 text-xs hover:bg-surface-hover ${
              index > 0 ? 'border-t' : ''
            } ${selected ? 'bg-surface-active text-text' : 'text-muted'}`}
          >
            <input
              type="radio"
              name="youtube-subtitle-track"
              value={track.id}
              checked={selected}
              onChange={() => onSelect(track.id)}
              className="sr-only"
            />
            <span
              className={`motion-surface h-2.5 w-2.5 rounded-full border ${
                selected ? 'border-primary bg-primary' : 'border-border-strong'
              }`}
              aria-hidden="true"
            />
            <span className="min-w-0 flex-1 truncate font-semibold">
              {languageName(track.language)}
            </span>
            <span className="rounded-full px-2 py-0.5 text-[10px] font-semibold text-muted">
              {track.isAutoGenerated ? 'авто' : 'авторские'}
            </span>
          </label>
        );
      })}
    </div>
  );
}
