[package]
name = "application"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
domain = { path = "../domain" }
ports = { path = "../ports" }
thiserror.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["sync", "time", "rt", "macros", "fs"] }
uuid = { workspace = true, features = ["v4"] }
tempfile.workspace = true
bytes = "1.12.1"
tracing.workspace = true
futures.workspace = true
tokio-util = "0.7"

[dev-dependencies]
sqlx = { workspace = true }
adapters-storage = { path = "../adapters-storage" }
adapters-ytdlp = { path = "../adapters-ytdlp" }
adapters-model = { path = "../adapters-model" }
adapters-ffmpeg = { path = "../adapters-ffmpeg" }
tempfile.workspace = true
chrono.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
