[package]
name = "adapters-tauri"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tauri = { workspace = true, features = [] }
tauri-plugin-shell.workspace = true
serde = { workspace = true, features = ["derive"] }
application.workspace = true
domain.workspace = true
ports.workspace = true
common.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["sync", "fs"] }
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
chrono.workspace = true
tempfile.workspace = true

[lints]
workspace = true
