[package]
name = "adapters-tauri"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tauri = { workspace = true, features = [] }
tauri-plugin-shell.workspace = true
serde = { workspace = true, features = ["derive"] }
application = { path = "../application" }
domain = { path = "../domain" }
ports = { path = "../ports" }
common = { version = "0.1.0", path = "../common" }
async-trait.workspace = true
tokio = { workspace = true, features = ["sync", "fs"] }
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
chrono.workspace = true
tempfile.workspace = true

[lints]
workspace = true
