use async_trait::async_trait;

use domain::media::{Artifact, ArtifactKind, SynthesizedSegment};
use domain::transcript::{Transcript, TranscriptSegment};
use ports::engine::{AsrEnginePort, SynthesizeSpeechRequest, TtsEnginePort};
use ports::error::PortError;

pub struct MockAsrEngineAdapter;

impl Default for MockAsrEngineAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl MockAsrEngineAdapter {
    pub fn new() -> Self {
        Self
    }
}

#[async_trait]
impl AsrEnginePort for MockAsrEngineAdapter {
    async fn transcribe_audio(&self, _audio_artifact: &Artifact) -> Result<Transcript, PortError> {
        Ok(Transcript {
            language: "en".to_string(),
            segments: vec![
                TranscriptSegment {
                    id: domain::transcript::TranscriptSegmentId(uuid::Uuid::new_v4()),
                    index: 0,
                    start_ms: 0,
                    end_ms: 2000,
                    source_text: "Welcome to Auralis.".to_string(),
                    translated_text: None,
                    adapted_text: None,
                    speaker: None,
                    confidence: None,
                },
                TranscriptSegment {
                    id: domain::transcript::TranscriptSegmentId(uuid::Uuid::new_v4()),
                    index: 1,
                    start_ms: 2000,
                    end_ms: 5000,
                    source_text: "This is a mock transcript generated by the backend.".to_string(),
                    translated_text: None,
                    adapted_text: None,
                    speaker: None,
                    confidence: None,
                },
            ],
        })
    }
}

pub struct MockTtsEngineAdapter;

impl Default for MockTtsEngineAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl MockTtsEngineAdapter {
    pub fn new() -> Self {
        Self
    }
}

#[async_trait]
impl TtsEnginePort for MockTtsEngineAdapter {
    async fn synthesize_segments(
        &self,
        request: SynthesizeSpeechRequest,
    ) -> Result<Vec<SynthesizedSegment>, PortError> {
        let mut segments = Vec::new();
        for segment in request.transcript.segments {
            let path = request
                .target_dir
                .join(format!("mock_tts_{}.wav", segment.id.0));
            segments.push(SynthesizedSegment {
                segment_id: segment.id,
                audio_artifact: Artifact {
                    id: domain::media::ArtifactId(uuid::Uuid::new_v4()),
                    kind: ArtifactKind::GeneratedSpeechSegment,
                    location: domain::media::ArtifactLocation::LocalPath(
                        path.to_string_lossy().to_string(),
                    ),
                    size_bytes: None,
                },
                duration_ms: Some(segment.end_ms - segment.start_ms),
            });
        }
        Ok(segments)
    }
}
