[package]
name = "domain"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
base64 = "0.22.1"
chrono = { workspace = true, features = ["serde"] }
thiserror.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
