import { useEffect } from 'react';
import { cancelJob, subscribeJobEvents } from '@/entities/job';
import { importLocalMedia } from '@/entities/media';
import {
  createProject,
  createProjectFromYoutube,
  renameProject,
  startProjectMockPipeline,
} from '@/entities/project';
import type { Artifact } from '@/shared/api/contracts';
import { invoke } from '@/shared/api/tauri';

const READY_TIMEOUT_MS = 20_000;
const POLL_INTERVAL_MS = 50;
let started = false;

export function NativeE2ERunner() {
  useEffect(() => {
    if (started) return;
    started = true;
    void runNativeScenario();
  }, []);

  return null;
}

async function runNativeScenario() {
  const runId = __NATIVE_E2E_RUN_ID__;
  const projectIds: string[] = [];
  let unlisten: (() => void) | undefined;

  try {
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'react-started' });
    const project = await createProject(`native-e2e-running:${runId}`);
    projectIds.push(project.id);
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'project-created' });

    let observedJobId: string | undefined;
    let resolveCancelling!: () => void;
    const cancellingObserved = new Promise<void>((resolve) => {
      resolveCancelling = resolve;
    });
    unlisten = await withTimeout(
      subscribeJobEvents((event) => {
        if (event.job.id === observedJobId && event.job.status === 'cancelling') {
          resolveCancelling();
        }
      }),
      'Timed out registering the job event listener',
    );
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'listener-ready' });

    await importLocalMedia(project.id, __NATIVE_E2E_MEDIA_PATH__);
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'source-imported' });
    const artifact = await waitForSourceArtifact(project.id);
    const resolvedPath = await invoke('resolve_artifact_path_cmd', { artifactId: artifact.id });

    if (artifact.location.kind !== 'storageKey' || !resolvedPath.trim()) {
      throw new Error('Native artifact did not resolve to managed storage');
    }

    const pipeline = await startProjectMockPipeline(project.id, {
      id: 'native-e2e-vtt',
      language: 'en',
      label: 'Native E2E',
      format: 'vtt',
      isAutoGenerated: false,
    });
    observedJobId = pipeline.job.id;
    await waitForPipelinePause();
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'pipeline-paused' });

    const cancellation = cancelJob(pipeline.job.id);
    await withTimeout(cancellingObserved, 'Timed out waiting for the cancelling event');
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'cancelling-observed' });
    const cancelled = await withTimeout(cancellation, 'Timed out waiting for cancellation');
    if (cancelled.status !== 'cancelled') {
      throw new Error(`Cancellation returned ${cancelled.status}`);
    }
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'cancelled-returned' });
    await waitForProjectStatus(project.id, 'cancelled');
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'project-cancelled' });

    const youtubeProject = await createProjectFromYoutube(__NATIVE_E2E_YTDLP_URL__);
    projectIds.push(youtubeProject.id);
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'ytdlp-import-returned' });

    const downloadedArtifact = await waitForReadyArtifact(youtubeProject.id, 'downloadedVideo');
    const downloadedPath = await invoke('resolve_artifact_path_cmd', {
      artifactId: downloadedArtifact.id,
    });
    if (downloadedArtifact.location.kind !== 'storageKey' || !downloadedPath.trim()) {
      throw new Error('yt-dlp artifact did not resolve to managed storage');
    }

    const pendingImports = await invoke('list_pending_youtube_imports_cmd');
    if (pendingImports.length !== 0) {
      throw new Error('Completed native yt-dlp import retained its journal entry');
    }
    await renameProject(
      youtubeProject.id,
      `native-e2e-ytdlp-complete:${runId}`,
      youtubeProject.revision,
    );
    await invoke('native_e2e_checkpoint_cmd', { checkpoint: 'ytdlp-project-ready' });

    const latestProject = await invoke('get_project_cmd', { projectId: project.id });
    await renameProject(project.id, `native-e2e-complete:${runId}`, latestProject.revision);
  } catch (error) {
    console.error('Native E2E scenario failed', error);
    if (projectIds[0]) {
      const projectId = projectIds[0];
      await invoke('get_project_cmd', { projectId })
        .then((current) => renameProject(projectId, `native-e2e-failed:${runId}`, current.revision))
        .catch(() => undefined);
    }
  } finally {
    unlisten?.();
  }
}

async function waitForPipelinePause(): Promise<void> {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  while (Date.now() < deadline) {
    if (await invoke('native_e2e_pipeline_pause_reached_cmd')) return;
    await delay(POLL_INTERVAL_MS);
  }
  throw new Error('Timed out waiting for the deterministic pipeline pause');
}

async function waitForProjectStatus(projectId: string, expected: string): Promise<void> {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  while (Date.now() < deadline) {
    if ((await invoke('get_project_cmd', { projectId })).status === expected) return;
    await delay(POLL_INTERVAL_MS);
  }
  throw new Error(`Timed out waiting for project status ${expected}`);
}

async function withTimeout<T>(promise: Promise<T>, message: string): Promise<T> {
  return Promise.race([
    promise,
    delay(READY_TIMEOUT_MS).then(() => {
      throw new Error(message);
    }),
  ]);
}

async function waitForSourceArtifact(projectId: string): Promise<Artifact> {
  return waitForReadyArtifact(projectId, 'sourceVideo');
}

async function waitForReadyArtifact(
  projectId: string,
  kind: 'sourceVideo' | 'downloadedVideo',
): Promise<Artifact> {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const artifacts = await invoke('list_project_artifacts_cmd', {
      projectId,
      kind,
    });
    const ready = artifacts.find((artifact) => artifact.state === 'ready');
    if (ready) return ready;
    await delay(POLL_INTERVAL_MS);
  }
  throw new Error(`Timed out waiting for the ${kind} artifact to become ready`);
}

function delay(durationMs: number) {
  return new Promise<void>((resolve) => setTimeout(resolve, durationMs));
}
