use adapters_storage::memory::InMemoryProjectRepository;
use adapters_ytdlp::mock::MockVideoSourceAdapter;
use application::usecases::pipeline::start_mock::{
    StartMockPipelineRequest, StartMockPipelineUseCase,
};
use application::usecases::project::create::{CreateProjectRequest, CreateProjectUseCase};
use application::usecases::project::import_source::{
    ImportVideoSourceRequest, ImportVideoSourceUseCase,
};
use domain::media::MediaSource;
use domain::project::Project;
use jobs::id::JobId;
use jobs::job::Job;
use jobs::manager::JobManager;
use serde::Serialize;
use std::sync::Arc;
use tauri::{Emitter, Manager, State};

#[derive(Serialize)]
pub struct ProjectDto {
    pub id: String,
    pub title: String,
    pub status: String,
}

impl From<&Project> for ProjectDto {
    fn from(p: &Project) -> Self {
        Self {
            id: p.id().to_string(),
            title: p.title().to_string(),
            status: format!("{:?}", p.status()),
        }
    }
}

#[derive(Serialize)]
pub struct CreateProjectResponse {
    pub project: ProjectDto,
    pub job: Job,
}

#[tauri::command]
async fn create_project_from_youtube_cmd(
    url: String,
    state: State<'_, JobManager>,
    project_repo: State<'_, InMemoryProjectRepository>,
) -> Result<CreateProjectResponse, String> {
    // 1. Create Project
    let create_use_case = CreateProjectUseCase::new(project_repo.inner().clone());
    let req = CreateProjectRequest { title: url.clone() };
    let create_res = create_use_case
        .execute(req)
        .await
        .map_err(|e| format!("{:?}", e))?;

    // 2. Import Video Source
    let mock_video_source = MockVideoSourceAdapter::new();
    let import_use_case =
        ImportVideoSourceUseCase::new(project_repo.inner().clone(), mock_video_source);
    let source = MediaSource::RemoteUrl { url };
    let req2 = ImportVideoSourceRequest {
        project_id: create_res.project.id().clone(),
        source,
    };
    let import_res = import_use_case
        .execute(req2)
        .await
        .map_err(|e| format!("{:?}", e))?;

    // 3. Start Mock Pipeline
    let pipeline_use_case =
        StartMockPipelineUseCase::new(project_repo.inner().clone(), state.inner().clone());
    let req3 = StartMockPipelineRequest {
        project_id: import_res.project.id().clone(),
    };
    let response = pipeline_use_case
        .execute(req3)
        .await
        .map_err(|e| format!("{:?}", e))?;

    Ok(CreateProjectResponse {
        project: ProjectDto::from(&response.project),
        job: response.job,
    })
}

#[derive(Serialize)]
pub struct TranscriptDto {
    pub language: String,
    pub segments: Vec<TranscriptSegmentDto>,
}

#[derive(Serialize)]
pub struct TranscriptSegmentDto {
    pub id: String,
    pub index: u32,
    pub start_ms: u64,
    pub end_ms: u64,
    pub source_text: String,
}

#[tauri::command]
async fn get_transcript_cmd(_project_id: String) -> Result<Option<TranscriptDto>, String> {
    // For the mock phase, we just return a stub transcript
    // In reality, this would fetch from a TranscriptRepository using the project_id
    Ok(Some(TranscriptDto {
        language: "en".to_string(),
        segments: vec![
            TranscriptSegmentDto {
                id: "1".to_string(),
                index: 0,
                start_ms: 0,
                end_ms: 2000,
                source_text: "Welcome to Auralis.".to_string(),
            },
            TranscriptSegmentDto {
                id: "2".to_string(),
                index: 1,
                start_ms: 2000,
                end_ms: 5000,
                source_text: "This is a mock transcript generated by the backend.".to_string(),
            },
        ],
    }))
}

#[tauri::command]
fn run_dubbing_cmd(video_url: String) -> Result<String, String> {
    application::commands::run_dubbing(video_url)
}

#[tauri::command]
async fn health_check() -> Result<String, String> {
    Ok("ok".to_string())
}

#[tauri::command]
async fn start_mock_dubbing_job_cmd(
    input: String,
    state: State<'_, JobManager>,
) -> Result<Job, String> {
    let job_id = state.start_mock_dubbing_job(input, None).await;
    state
        .get_job(&job_id)
        .await
        .ok_or_else(|| "Failed to retrieve job".to_string())
}

#[tauri::command]
async fn list_jobs_cmd(state: State<'_, JobManager>) -> Result<Vec<Job>, String> {
    Ok(state.list_jobs().await)
}

#[tauri::command]
async fn cancel_job_cmd(job_id: String, state: State<'_, JobManager>) -> Result<Job, String> {
    let id = JobId(job_id);
    state.cancel_job(&id).await.map_err(|e| e.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .setup(|app| {
            let app_handle = app.handle().clone();

            let app_handle_clone = app_handle.clone();
            let emitter = Arc::new(move |event: jobs::event::JobEvent| {
                if event.status == jobs::status::JobStatus::Completed {
                    if let Some(project_id) = &event.project_id {
                        let _ = app_handle_clone.emit(
                            "transcript-ready",
                            serde_json::json!({
                                "projectId": project_id,
                                "jobId": event.job_id,
                            }),
                        );
                    }
                }
                let _ = app_handle_clone.emit("job-event", event);
            });
            let job_manager = JobManager::new(Some(emitter));

            let project_repo = InMemoryProjectRepository::new();

            app.manage(job_manager);
            app.manage(project_repo);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            create_project_from_youtube_cmd,
            get_transcript_cmd,
            run_dubbing_cmd,
            health_check,
            start_mock_dubbing_job_cmd,
            list_jobs_cmd,
            cancel_job_cmd
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
